CREATE TABLE IF NOT EXISTS docs (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  color TEXT NOT NULL DEFAULT 'blue',
  updated INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS sheets (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  cols TEXT NOT NULL DEFAULT '[]',
  rows TEXT NOT NULL DEFAULT '[]',
  color TEXT NOT NULL DEFAULT 'violet',
  updated INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS stickies (
  id TEXT PRIMARY KEY,
  body TEXT NOT NULL DEFAULT '',
  x INTEGER NOT NULL DEFAULT 40,
  y INTEGER NOT NULL DEFAULT 30,
  w INTEGER NOT NULL DEFAULT 200,
  h INTEGER NOT NULL DEFAULT 150,
  z INTEGER NOT NULL DEFAULT 1,
  color TEXT NOT NULL DEFAULT 'yellow',
  updated INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS reminders (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL DEFAULT '',
  "when" INTEGER,
  repeat TEXT NOT NULL DEFAULT 'once',
  enabled INTEGER NOT NULL DEFAULT 1,
  fired INTEGER NOT NULL DEFAULT 0,
  last_fired_date TEXT,
  source TEXT NOT NULL DEFAULT 'Remind',
  created_at INTEGER NOT NULL
);
